---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  document-start: disable
  truthy:
    allowed-values: ['true', 'false']

ignore-from-file: .gitignore
